### ISSUE TITLE
Number of occurrences of species in the training set

### ISSUE THREAD

**Issue by tony9664** [fteufel/SecretoGen#2]
Hi, it is possible to know the number of occurrences of the species in the training set. It should be able to tell which organism is better represented during training, therefore would give more trustworthy predictions.

**Comment by fteufel** [comment]
Hi, great question, here are the counts for each species:
[taxonomy_counts.csv](https://github.com/user-attachments/files/17149437/taxonomy_counts.csv)

Overall, as SecretoGen shares information across the phylogenetic tree when training, I would also take coverage of closely related organisms into account when judging applicability.

**Comment by tony9664** [comment]
Thank you! That is very helpful. May I ask another question: Are you working on evaluating the newly generated sequences experimentally? Are they working well?

**Comment by fteufel** [comment]
No, we are not working on experiments for now - only evaluated the library ranking approach.
